### PR TITLE
GitHub deploy page improvement

### PR DESCRIPTION
**Pull request by chiaweh2**
The PR is mainly to address the bug in search functionality. The bug appear in when using the keyword i.e. NOAA PSL. The related resource box did not appear as expected. The fix is mainly in the javascript section of the browse.html templating file.

Some other minor improvements include 
1. redesign some icon and logo that makes it more specific to the CEFI theme.
2. fixing the variable keyword which show a array instead of the first element of variable name
3. change of url to GitHub repo due to the transfer from old repo to new repo
4. fill in the CEFI description in the first landing page
5. cleaning up unused nav bar

### CODE REVIEW

**Comment by chiaweh2** [comment]
@MathewBiddle I made some adjustment to the original GitHub page that you created for the CEFI list. I was wondering do you have time to take a look at the changes. If not, it is totally fine! We can also merge the changes to be able to look at the deployed result and can role back or make new changes as we see fit. Would this sounds okay for you? Thank you again for initiate the page!

**Comment by MathewBiddle** [comment]
We should do some cleanup on the image names. I was just trying to checkout this branch 
```git
git checkout -b gh-test upstream/gh-test
error: invalid path 'images/coastal_resilience_toolkits_:_the_nature_conservancy.png'
```

We might have to fix the git history to remove those files and add the cleaned ones in later.

**Comment by chiaweh2** [comment]
Ah. I will try to work on this today.

**Comment by chiaweh2** [comment]
@MathewBiddle sorry for the late fix. I change the filename and the filename in the json file.

**Comment by MathewBiddle** [comment]
blerg, I'm still running into this issue.

```bash
$ git checkout -b gh-test upstream/gh-test
error: invalid path 'images/coastal_resilience_toolkits_:_the_nature_conservancy.png'
```

I think there might be some tricks with Git for Windows that I can do to fix this. I'll keep testing.

**Comment by chiaweh2** [comment]
Oh! hmm.. maybe it is related to the file git history? Let me see if I can fix this from my side.

**Comment by chiaweh2** [comment]
it seems like if I want to remove the file from a git history I will need to force push and all collaborator will need to rebase. I am thinking to remove the history of the image file in question. Would this work for you? I will listed out the remove file if this is the route that we want to go forward. Please let me know!

**Comment by chiaweh2** [comment]
@MathewBiddle I have the cleaned git history ready but this means the file in question/error will be removed entirely from the git history as if it never existed. I have added the file with the proper name back to the newest commit. I have not force push this change yet since I think it will also change the entire git history (all branches) on GitHub too. I am not sure from your end if you only need to rebase or you will need to clone a new repo entirely. Please feel free to let me know if you want to proceed from this method or you found a way to fix it from your end.

**Comment by chiaweh2** [comment]
File name changes :
1. coastal_resilience_toolkits_:_the_nature_conservancy.png => coastal_resilience_toolkits_the_nature_conservancy.png
2. california_marine_protected_area_(mpa)_dashboard.png => california_marine_protected_area_mpa_dashboard.png
3. applied_california_current_ecosystem_studies_(access)_mapping_tool.png => applied_california_current_ecosystem_studies_access_mapping_tool.png

**Comment by MathewBiddle** [comment]
@ocefpaf looking for some advice here. If I follow https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows I can set
```bash
git config core.protectNTFS false
```
and it could resolve the issue on my system. However, is that the 'right' approach?

**Comment by chiaweh2** [comment]
I was trying to search a way to "test deploy" the page that is in this branch through GitHub action but has not found one example or tutorial that I can understand and try it out yet. If anyone knows, please feel free to chime in!

**Comment by ocefpaf** [comment]
> I was trying to search a way to "test deploy" the page that is in this branch through GitHub action but has not found one example or tutorial that I can understand and try it out yet. If anyone knows, please feel free to chime in!

I know that folks uses [netfly](https://docs.netlify.com/cli/get-started/) for this. However, I never used it. I used in the past a setup that deployed a draft page using CircleCI, similar to what [matplotlib does here](https://github.com/matplotlib/matplotlib/tree/main/.circleci).

**Comment by chiaweh2** [comment]
@ocefpaf Thanks for sharing! I will look into circleCI for sure. @MathewBiddle do you by any chance had the chance to review the modifications? Thank you!

**Comment by MathewBiddle** [comment]
Finally it's working! Thanks for your patience @chiaweh2! Everything looks good to me. I like these changes.

**Comment by chiaweh2** [comment]
Thank you for the review! I am glad you like the changes!

**Comment by MathewBiddle** [comment]
sorry it took so long...

**Pull request merged**
